<script setup lang="ts">
</script>

<template>
  <div
    w-full
    flex
    flex-col
    items-center
  >
    <NuxtLink
      to="https://hackmd.io/@7veHo9V5QuuMVFc_R7KTGA/HJZ3aZSekl/"
      bg-black
      hover:bg-white
      w-full
      text-center
      justify-center
      py-14px
      cursor-pointer
      text-app-text-grey
      class="hover:text-black"
      hover:underline
      underline-offset-1
      text-16px
      font-400
      uppercase
    >
      About
    </NuxtLink>
    <NuxtLink
      to="https://mirror.xyz/0x0f1F3DAf416B74DB3DE55Eb4D7513a80F4841073/s9flkE6tMaJ4f2tzWu-FmDy7Zx_TRPe3jdXr2iYmYH0"
      bg-black
      hover:bg-white
      w-full
      text-center
      justify-center
      py-14px
      cursor-pointer
      text-app-text-grey
      class="hover:text-black"
      hover:underline
      underline-offset-1
      text-16px
      font-400
      uppercase
    >
      Scoring
    </NuxtLink>
    <NuxtLink
      bg-black
      hover:bg-white
      w-full
      flex
      gap-8px
      text-center
      items-center
      justify-center
      py-14px
      cursor-pointer
      text-app-text-grey
      class="hover:text-black"
      hover:underline
      underline-offset-1
      text-16px
      font-400
      uppercase
      to="https://github.com/web3privacy/privacy-projects-db"
    >
      LEARN HOW TO CONTRIBUTE
      <UnoIcon
        i-web-arrowright
        text-16px
        w-16px
        h-16px
      />
    </NuxtLink>
    <NuxtLink
      v-if="useRoute().path !== '/project/create'"
      bg-black
      hover:bg-white
      w-full
      flex
      sm:hidden
      gap-8px
      text-center
      items-center
      justify-center
      py-14px
      cursor-pointer
      text-app-text-grey
      to="/project/create"
      mr-16px
    >
      + ADD PROJECT
    </NuxtLink>
  </div>
</template>
